export const MIN_COUNT_TITLE = 2
export const MAX_COUNT_TITLE = 20

export const MIN_DESCRIPTION_COUNT = 10
export const MAX_DESCRIPTION_COUNT = 100
export const MIN_WEBSITE_URL_COUNT = 5

export const MIN_SHORT_DESCRIPTION_COUNT = 5
export const MAX_SHORT_DESCRIPTION_COUNT = 50

export const MIN_CONTENT_COUNT = 5

export const MAX_CONTENT_COUNT = 50

export default {
  VIDEOS: {
    MIN_COUNT_TITLE,
    MAX_COUNT_TITLE
  },
  BLOGS: {
    MIN_COUNT_TITLE,
    MAX_COUNT_TITLE: 19,
    MAX_DESCRIPTION_COUNT,
    MIN_WEBSITE_URL_COUNT,
    MIN_DESCRIPTION_COUNT
  },
  POSTS: {
    MIN_COUNT_TITLE,
    MAX_COUNT_TITLE,
    MIN_SHORT_DESCRIPTION_COUNT,
    MAX_SHORT_DESCRIPTION_COUNT,
    MIN_CONTENT_COUNT,
    MAX_CONTENT_COUNT
  }
}
